services:
  authelia:
    environment:
      X_AUTHELIA_CONFIG: /config/configuration.smtp.yml
      AUTHELIA_NOTIFIER_SMTP_ADDRESS: ${AUTHELIA_NOTIFIER_SMTP_ADDRESS}
      AUTHELIA_NOTIFIER_SMTP_USERNAME: ${AUTHELIA_NOTIFIER_SMTP_USERNAME}
      AUTHELIA_NOTIFIER_SMTP_PASSWORD: ${AUTHELIA_NOTIFIER_SMTP_PASSWORD}
      AUTHELIA_NOTIFIER_SMTP_SENDER: ${AUTHELIA_NOTIFIER_SMTP_SENDER}
      AUTHELIA_NOTIFIER_SMTP_IDENTIFIER: ${AUTHELIA_NOTIFIER_SMTP_IDENTIFIER:-trainlikea.pro}
      AUTHELIA_NOTIFIER_SMTP_STARTUP_CHECK_ADDRESS: ${AUTHELIA_NOTIFIER_SMTP_STARTUP_CHECK_ADDRESS}
