"""resize knowledge_chunks.embedding from 1536 to 768 dimensions

Revision ID: 20260806_000001
Revises: 20260805_000001
Create Date: 2026-08-03 00:00:00.000000

RAG embeddings moved from OpenAI text-embedding-3-small (1536) to the
configured provider at 768 dimensions (#515), so the pgvector column has to be
resized.

Existing vectors are *deleted* rather than converted: an embedding is only
comparable to others produced by the same model, so a 1536-dimension corpus is
worthless once queries are embedded by a different model. The corpus is
regenerated by re-running ``scripts/ingest_cycling_science.py``, which upserts
by (source_id, chunk_index) and is safe to run repeatedly. In production the
table held 0 rows when this was written, so nothing was lost there.
"""

from __future__ import annotations

from alembic import op
from sqlalchemy import inspect as sa_inspect


revision = "20260806_000001"
down_revision = "20260805_000001"
branch_labels = None
depends_on = None

_OLD_DIM = 1536
_NEW_DIM = 768


def _resize(dim: int) -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        # The SQLite fallback stores embeddings as JSON text and has no
        # dimension to resize.
        return
    if "knowledge_chunks" not in set(sa_inspect(bind).get_table_names()):
        return

    # Stale-dimension rows cannot be cast, and would be meaningless if they
    # could: they were produced by a different embedding model.
    op.execute("DELETE FROM knowledge_chunks")
    # The HNSW index is bound to the column's dimension and must be rebuilt.
    op.execute("DROP INDEX IF EXISTS knowledge_chunks_embedding_idx")
    op.execute(
        f"ALTER TABLE knowledge_chunks "
        f"ALTER COLUMN embedding TYPE vector({dim}) "
        f"USING embedding::vector({dim})"
    )
    op.execute(
        "CREATE INDEX knowledge_chunks_embedding_idx "
        "ON knowledge_chunks USING hnsw (embedding vector_cosine_ops)"
    )


def upgrade() -> None:
    _resize(_NEW_DIM)


def downgrade() -> None:
    _resize(_OLD_DIM)
